name = "default"

[schema.fish.linux.paths]
default = ["~/.config/fish"]

[schema.alacritty.windows.paths]
default = ["${APPDATA}/alacritty/alacritty.toml"]

[schema.alacritty.unix.paths]
default = [
  "${XDG_CONFIG_HOME}/alacritty/alacritty.toml",
  "${XDG_CONFIG_HOME}/alacritty.toml",
  "~/.config/alacritty/alacritty.toml",
  "~/.alacritty.toml",
]

[schema.git.unknown.paths]
default = ["~/.gitconfig"]

[schema.nvim.unix.paths]
default = ["${XDG_CONFIG_HOME}/nvim", "~/.config/nvim"]

[schema.nvim.windows.paths]
default = ["${XDG_CONFIG_HOME}/nvim", "~/AppData/Local/nvim"]

[schema.yakuake.linux.paths]
default = ["~/.config/yakuakerc"]

[schema.zellij.linux.paths]
default = ["${ZELLIJ_CONFIG_DIR}", "~/.config/zellij"]

[schema.acme.linux.paths]
default = ["~/.acme.sh"]

[schema.konsole.manjaro.paths]
default = ["~/.config/konsolerc"]
data = ["~/.local/share/konsole"]

[schema.oli.linux.paths]
default = ["~/.config/oli"]

[schema.google-chrome.linux.paths]
default = ["~/.config/chrome-flags.conf"]

[schema.jujutsu.linux.paths]
default = ["~/.config/jj"]
